"""A package of workflow functions to work with sfle

Workflow functions take the oo env from sfle along with a list of files to process.

These functions return a list of output files generated by the function
"""

import re
import sys

from ... import (
    settings
)

from .sixteen import (
    demultiplex,
    pick_otus_closed_ref
)

from .wgs import (
    metaphlan2
)


def all():
    return dict( 
        (item.func_name, item)
        for item in sys.modules[__name__].__dict__.itervalues()
        if getattr(item, "func_name", None) 
        and getattr(item, "func_doc", None) 
        and re.match(r'^[Ww]orkflow', item.func_doc.strip())
    )

